plugins {
	id 'base'
	id 'org.asciidoctor.jvm.convert' version '4.0.5'
	id 'org.asciidoctor.jvm.pdf' version '4.0.5'
}

group = 'io.datadynamics.asciidoc'
description = 'AsciiDoc Sample'

repositories {
	mavenCentral()
}

configurations {
	documentation
}

asciidoctorj {
	version = '3.0.1'
	modules {
		pdf {
			version '2.3.27'
		}
	}
	attributes 'source-highlighter': 'rouge'
}

asciidoctor {
	sourceDir file('src/docs/asciidoc')
	sources {
		include 'index.adoc'
	}
	baseDirFollowsSourceDir()
}

asciidoctorPdf {
	sourceDir file('src/docs/asciidoc')
	sources {
		include 'index.adoc'
	}
	baseDirFollowsSourceDir()
	attributes 'pdf-theme': file('src/docs/theme/DataDynamics-theme.yml').absolutePath,
	           'pdf-fontsdir': file('src/docs/theme').absolutePath
}

def zipDocs = tasks.register('zip', Zip) {
	dependsOn tasks.named('asciidoctor'), tasks.named('asciidoctorPdf')
	duplicatesStrategy = DuplicatesStrategy.FAIL
	from(tasks.named('asciidoctorPdf').map { it.outputDir }) {
		into 'reference/pdf'
		rename 'index.pdf', "${project.name}-reference.pdf"
	}
	from(tasks.named('asciidoctor').map { it.outputDir }) {
		into 'reference/htmlsingle'
	}
}

artifacts {
	documentation zipDocs
}

tasks.named('build') {
	dependsOn zipDocs
}

configurations.configureEach {
	resolutionStrategy.cacheChangingModulesFor 0, 'minutes'
}
